<?php

/**
 * @file
 * Sandwich module.
 */
use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function sandwich_theme() {
  return [
    'sandwich' => [
      'variables' => [
        'attributes' => [],
        'name' => '',
        'bread' => '',
        'cheese' => '',
        'veggies' => [],
        'protein' => '',
        'condiments' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_sandwich().
 */
function sandwich_theme_suggestions_sandwich($variables) {
  return 'sandwich__' . Html::cleanCssIdentifier($variables['name']);
}

/**
 * Implements hook_theme_suggestions_sandwich_alter().
 */
function sandwich_theme_suggestions_sandwich_alter(&$suggestions, $variables) {
}

/**
 * Implements template_preprocess_sandwich().
 */
function template_preprocess_sandwich(&$variables) {
}

/**
 * Implements hook_preprocess_sandwich().
 */
function sandwich_preprocess_sandwich(&$variables) {
}
